spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/livecloud?useUnicode=true&useSSL=false&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: your_user_name
    password: your_pass_word
  redis:
    # Redis数据库索引（默认为0）
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码
    password: your_pass_word
