spring:
  datasource:
    url: jdbc:mysql://114.116.219.138:3306/livecloud?useUnicode=true&useSSL=false&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: livecloud
    password: admin123
  redis:
    # Redis数据库索引（默认为0）
    # Redis服务器地址
    host: 114.116.219.138
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: China099
  flyway:
    out-of-order: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl